f

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -32,7 +32,7 @@ jobs:
           CYPRESS_ENV_JSON: ${{ secrets.CYPRESS_ENV_JSON }}
 
       - name: Debug cypress.env.json
-        run: cat cypress.env.json || echo "Failed to create cypress.env.json"
+        run: cat cypress.env.json || echo "Fail to create cypress.env.json"
 
       - name: Install dependencies
         run: npm install
